# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNGrid' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNGrid
  target pod "HockeySDK" do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNGridTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RNGrid-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNGrid-tvOS

  target 'RNGrid-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
